package pl.ug.NestPoint.mapper;

import org.mapstruct.*;
import pl.ug.NestPoint.domain.Message;
import pl.ug.NestPoint.dto.MessageDTO;

@Mapper(componentModel = "spring")
public interface MessageMapper {
    
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "sender", ignore = true)           // Set manually in ChatService
    @Mapping(target = "conversation", ignore = true)     // Set manually in ChatService
    @Mapping(target = "timestamp", ignore = true)        // Auto-generated by @PrePersist
    @Mapping(target = "isRead", constant = "false")    
    Message toEntity(MessageDTO messageDTO);
    
    @Mapping(source = "conversation.id", target = "conversationId")
    @Mapping(source = "sender.id", target = "senderId")
    @Mapping(expression = "java(message.getSender() != null ? message.getSender().getFirstName() + \" \" + message.getSender().getLastName() : \"Unknown\")", target = "senderName")
    @Mapping(target = "currentUserSender", ignore = true)  // Set manually in ChatService
    MessageDTO toDTO(Message message);
}